defmodule SignsUI.Signs.Names do

  def sign_routes() do
    %{
      mattapan: "Mattapan",
      silver: "Silver Line",
      blue: "Blue Line",
      orange: "Orange Line",
      red: "Red Line",
    }
  end

  def mattapan() do
    [
      {"ashmont_mezzanine", "Ashmont Mezzanine"},
      {"cedar_grove_outbound", "Cedar Grove Outbound"},
      {"cedar_grove_inbound", "Cedar Grove Inbound"},
      {"butler_center", "Butler Center"},
      {"milton_outbound", "Milton Outbound"},
      {"milton_inbound", "Milton Inbound"},
      {"central_avenue_outbound", "Central Avenue Outbound"},
      {"central_avenue_inbound", "Central Avenue Inbound"},
      {"valley_road_outbound", "Valley Road Outbound"},
      {"valley_road_inbound", "Valley Road Inbound"},
      {"capen_street_outbound", "Capen Street Outbound"},
      {"capen_street_inbound", "Capen Street Inbound"},
    ]
  end

  def silver_line() do
    [
      {"chelsea_inbound", "Chelsea Inbound"},
      {"bellingham_square_inbound", "Bellingham Square Inbound"},
      {"bellingham_square_outbound", "Bellingham Square Outbound"},
      {"box_district_inbound", "Box District Inbound"},
      {"box_district_outbound", "Box District Outbound"},
      {"eastern_ave_inbound", "Eastern Ave Inbound"},
      {"eastern_ave_outbound", "Eastern Ave Outbound"},
      {"south_station_silver_line_outbound", "South Station Silver Line Outbound"},
      {"courthouse_station_outbound", "Courthouse Station Outbound"},
      {"world_trade_center_outbound", "World Trade Center Outbound"},
      {"world_trade_center_mezzanine", "World Trade Center Mezzanine"},
      {"courthouse_station_mezzanine", "Courthouse Station Mezzanine"},
      {"south_station_mezzanine", "South Station Mezzanine"},
    ]
  end

  def blue_line() do
    [
      {"wonderland_westbound", "Wonderland Westbound"},
      {"wonderland_mezzanine", "Wonderland Mezzanine"},
      {"revere_beach_eastbound", "Revere Beach Eastbound"},
      {"revere_beach_mezzanine", "Revere Beach Mezzanine"},
      {"revere_beach_westbound", "Revere Beach Westbound"},
      {"beachmont_westbound", "Beachmont Westbound"},
      {"beachmont_eastbound", "Beachmont Eastbound"},
      {"suffolk_downs_eastbound", "Suffolk Downs Eastbound"},
      {"suffolk_downs_westbound", "Suffolk Downs Westbound"},
      {"orient_heights_eastbound", "Orient Heights Eastbound"},
      {"orient_heights_mezzanine", "Orient Heights Mezzanine"},
      {"orient_heights_westbound", "Orient Heights Westbound"},
      {"wood_island_eastbound", "Wood Island Eastbound"},
      {"wood_island_mezzanine", "Wood Island Mezzanine"},
      {"wood_island_westbound", "Wood Island Westbound"},
      {"airport_eastbound", "Airport Eastbound"},
      {"airport_westbound", "Airport Westbound"},
      {"maverick_eastbound", "Maverick Eastbound"},
      {"maverick_westbound", "Maverick Westbound"},
      {"aquarium_eastbound", "Aquarium Eastbound"},
      {"aquarium_mezzanine", "Aquarium Mezzanine"},
      {"aquarium_westbound", "Aquarium Westbound"},
      {"state_blue_eastbound", "State Eastbound"},
      {"state_blue_mezzanine", "State Mezzanine"},
      {"state_blue_westbound", "State Westbound"},
      {"government_center_eastbound", "Government Center Eastbound"},
      {"government_center_mezzanine", "Government Center Mezzanine"},
      {"government_center_westbound", "Government Center Westbound"},
      {"bowdoin_eastbound", "Bowdoin Eastbound"},
      {"bowdoin_mezzanine", "Bowdoin Mezzanine"},
    ]
  end

  def orange_line() do
    [
      {"oak_grove_mezzanine_southbound", "Oak Grove Mezzanine Southbound"},
      {"oak_grove_northbound", "Oak Grove Northbound"},
      {"oak_grove_southbound", "Oak Grove Southbound"},
      {"oak_grove_east_busway", "Oak Grove East Busway"},
      {"malden_center_entire_station", "Malden Center Entire Station"},
      {"wellington_mezzanine", "Wellington Mezzanine"},
      {"wellington_northbound", "Wellington Northbound"},
      {"wellington_southbound", "Wellington Southbound"},
      {"assembly_mezzanine", "Assembly Mezzanine"},
      {"assembly_northbound", "Assembly Northbound"},
      {"assembly_southbound", "Assembly Southbound"},
      {"sullivan_mezzanine", "Sullivan Mezzanine"},
      {"sullivan_northbound", "Sullivan Northbound"},
      {"sullivan_southbound", "Sullivan Southbound"},
      {"community_college_mezzanine", "Community College Mezzanine"},
      {"community_college_northbound", "Community College Northbound"},
      {"community_college_southbound", "Community College Southbound"},
      {"orange_north_station_northbound", "Orange North Station Northbound"},
      {"orange_north_station_southbound", "Orange North Station Southbound"},
      {"orange_north_station_mezzanine", "Orange North Station Mezzanine"},
      {"orange_north_station_commuter_rail_exit", "Orange North Station Commuter Rail Exit"},
      {"orange_haymarket_mezzanine", "Orange Haymarket Mezzanine"},
      {"orange_haymarket_northbound", "Orange Haymarket Northbound"},
      {"orange_haymarket_southbound", "Orange Haymarket Southbound"},
      {"orange_state_mezzanine", "Orange State Mezzanine"},
      {"orange_state_northbound", "Orange State Northbound"},
      {"orange_state_southbound", "Orange State Southbound"},
      {"orange_downtown_crossing_northbound", "Orange Downtown Crossing Northbound"},
      {"orange_downtown_crossing_southbound", "Orange Downtown Crossing Southbound"},
      {"chinatown_northbound_lobby", "Chinatown Northbound Lobby"},
      {"chinatown_southbound_lobby", "Chinatown Southbound Lobby"},
      {"chinatown_northbound", "Chinatown Northbound"},
      {"chinatown_southbound", "Chinatown Southbound"},
      {"tufts_mezzanine", "Tufts Mezzanine"},
      {"tufts_northbound", "Tufts Northbound"},
      {"tufts_southbound", "Tufts Southbound"},
      {"back_bay_mezzanine", "Back Bay Mezzanine"},
      {"back_bay_northbound", "Back Bay Northbound"},
      {"back_bay_southbound", "Back Bay Southbound"},
      {"mass_ave_mezzanine", "Mass Ave Mezzanine"},
      {"mass_ave_northbound", "Mass Ave Northbound"},
      {"mass_ave_southbound", "Mass Ave Southbound"},
      {"ruggles_northbound", "Ruggles Northbound"},
      {"ruggles_southbound", "Ruggles Southbound"},
      {"ruggles_center", "Ruggles Center"},
      {"ruggles_mezzanine", "Ruggles Mezzanine"},
      {"roxbury_crossing_mezzanine", "Roxbury Crossing Mezzanine"},
      {"roxbury_crossing_northbound", "Roxbury Crossing Northbound"},
      {"roxbury_crossing_southbound", "Roxbury Crossing Southbound"},
      {"jackson_square_mezzanine", "Jackson Square Mezzanine"},
      {"jackson_square_northbound", "Jackson Square Northbound"},
      {"jackson_square_southbound", "Jackson Square Southbound"},
      {"stony_brook_mezzanine", "Stony Brook Mezzanine"},
      {"stony_brook_northbound", "Stony Brook Northbound"},
      {"stony_brook_southbound", "Stony Brook Southbound"},
      {"green_street_mezzanine", "Green Street Mezzanine"},
      {"green_street_northbound", "Green Street Northbound"},
      {"green_street_southbound", "Green Street Southbound"},
      {"forest_hills_main_lobby", "Forest Hills Main Lobby"},
      {"forest_hills_northbound", "Forest Hills Northbound"},
      {"forest_hills_southbound", "Forest Hills Southbound"},
      {"forest_hills_entrances_from_busways", "Forest Hills Entrances From Busways"},
      {"ruggles_upper_busway", "Ruggles Upper Busway"}
    ]
  end

  def red_line() do
    [
      {"alewife_center_southbound", "Alewife Center Southbound"},
      {"alewife_mezzanine_southbound", "Alewife Mezzanine Southbound"},
      {"davis_mezzanine", "Davis Mezzanine"},
      {"davis_northbound", "Davis Northbound"},
      {"davis_southbound", "Davis Southbound"},
      {"porter_mezzanine", "Porter Mezzanine"},
      {"porter_northbound", "Porter Northbound"},
      {"porter_southbound", "Porter Southbound"},
      {"harvard_mezzanine", "Harvard Mezzanine"},
      {"harvard_northbound", "Harvard Northbound"},
      {"harvard_southbound", "Harvard Southbound"},
      {"central_northbound", "Central Northbound"},
      {"central_southbound", "Central Southbound"},
      {"kendall_mit_northbound", "Kendall/MIT Northbound"},
      {"kendall_mit_southbound", "Kendall/MIT Southbound"},
      {"charles_mgh_northbound", "Charles MGH Northbound"},
      {"charles_mgh_southbound", "Charles MGH Southbound"},
      {"red_park_st_northbound", "Red Park St. Northbound"},
      {"red_park_st_southbound", "Red Park St. Southbound"},
      {"red_park_st_center", "Red Park St. Center"},
      {"red_downtown_crossing_northbound", "Red Downtown Crossing Northbound"},
      {"red_downtown_crossing_southbound", "Red Downtown Crossing Southbound"},
      {"red_south_station_mezzanine", "Red South Station Mezzanine"},
      {"red_south_station_northbound", "Red South Station Northbound"},
      {"red_south_station_southbound", "Red South Station Southbound"},
      {"south_station_silver_line_arrival_platform", "South Station Silver Line Arrival Platform"},
      {"jfk_umass_ashmont_platform_southbound", "JFK/UMass (Ashmont Platform) Southbound"},
      {"jfk_umass_braintree_platform_southbound", "JFK/UMass (Braintree Platform) Southbound"},
      {"jfk_umass_ashmont_platform_northbound", "JFK/UMass (Ashmont Platform) Northbound"},
      {"jfk_umass_braintree_platform_northbound", "JFK/UMass (Braintree Platform) Northbound"},
      {"jfk_umass_mezzanine", "JFK/UMass Mezzanine"},
      {"broadway_mezzanine", "Broadway Mezzanine"},
      {"broadway_northbound", "Broadway Northbound"},
      {"broadway_southbound", "Broadway Southbound"},
      {"andrew_mezzanine", "Andrew Mezzanine"},
      {"andrew_northbound", "Andrew Northbound"},
      {"andrew_southbound", "Andrew Southbound"},
      {"savin_hill_mezzanine", "Savin Hill Mezzanine"},
      {"savin_hill_northbound", "Savin Hill Northbound"},
      {"savin_hill_southbound", "Savin Hill Southbound"},
      {"fields_corner_mezzanine", "Fields Corner Mezzanine"},
      {"fields_corner_northbound", "Fields Corner Northbound"},
      {"fields_corner_southbound", "Fields Corner Southbound"},
      {"shawmut_mezzanine", "Shawmut Mezzanine"},
      {"shawmut_northbound", "Shawmut Northbound"},
      {"shawmut_southbound", "Shawmut Southbound"},
      {"ashmont_mezzanine", "Ashmont Mezzanine"},
      {"red_ashmont_northbound", "Ashmont Northbound"},
      {"north_quincy_mezzanine", "North Quincy Mezzanine"},
      {"north_quincy_northbound", "North Quincy Northbound"},
      {"north_quincy_southbound", "North Quincy Southbound"},
      {"wollaston_mezzanine", "Wollaston Mezzanine"},
      {"wollaston_northbound", "Wollaston Northbound"},
      {"wollaston_southbound", "Wollaston Southbound"},
      {"quincy_center_mezzanine", "Quincy Center Mezzanine"},
      {"quincy_center_northbound", "Quincy Center Northbound"},
      {"quincy_center_southbound", "Quincy Center Southbound"},
      {"quincy_adams_mezzanine", "Quincy Adams Mezzanine"},
      {"quincy_adams_northbound", "Quincy Adams Northbound"},
      {"quincy_adams_southbound", "Quincy Adams Southbound"},
      {"braintree_center_northbound", "Braintree Center Northbound"},
      {"braintree_mezzanine_northbound", "Braintree Mezzanine Northbound"},
    ]
  end

  def arinc_order do
    [
      ["Red Line", ["RALE", "RDAV", "RPOR", "RHAR", "RCEN", "RKEN", "RMGH", "RPRK", "RDTC", "RSOU", "SSOU", "RBRO", "RAND", "RSAV", "RFIE", "RSHA", "RASH", "RNQU", "RWOL", "RQUC", "RQUA", "RBRA", "RJFK"]],
      ["Orange Line", ["OOAK", "OMAL", "OWEL", "OASQ", "OSUL", "OCOM", "ONST", "OHAH", "OSTN", "OSTS", "ODTN", "ODTS", "OCHN", "OCHS", "ONEM", "OBAC", "OMAS", "ORUG", "OROX", "OJAC", "OSTO", "OGRE", "OFOR", "SFOR", "SRUG"]],
      ["Blue Line", ["BWON", "BREV", "BBEA", "BSUF", "BORH", "BWOO", "BAIR", "BMAV", "BAQU", "BSTA", "BGOV"]],
      ["Silver Line", ["SCHS", "SBSQ", "SBOX", "SEAV", "SSOU", "SCOU", "RSOU", "SWTC"]],
      ["Mattapan", ["RASH", "MCED", "MBUT", "MMIL", "MCEN", "MVAL", "MCAP"]],
    ]
  end

  def arinc_ids do
    id_to_id = %{
      "BAIR-e" => "airport_eastbound",
      "BAIR-w" => "airport_westbound",
      "BAQU-e" => "aquarium_eastbound",
      "BAQU-m" => "aquarium_mezzanine",
      "BAQU-w" => "aquarium_westbound",
      "BBEA-e" => "beachmont_eastbound",
      "BBEA-w" => "beachmont_westbound",
      "BBOW-e" => "bowdoin_eastbound",
      "BBOW-m" => "bowdoin_mezzanine",
      "BGOV-e" => "government_center_eastbound",
      "BGOV-m" => "government_center_mezzanine",
      "BGOV-w" => "government_center_westbound",
      "BMAV-e" => "maverick_eastbound",
      "BMAV-w" => "maverick_westbound",
      "BORH-e" => "orient_heights_eastbound",
      "BORH-m" => "orient_heights_mezzanine",
      "BORH-w" => "orient_heights_westbound",
      "BREV-e" => "revere_beach_eastbound",
      "BREV-m" => "revere_beach_mezzanine",
      "BREV-w" => "revere_beach_westbound",
      "BSTA-e" => "state_blue_eastbound",
      "BSTA-m" => "state_blue_mezzanine",
      "BSTA-w" => "state_blue_westbound",
      "BSUF-e" => "suffolk_downs_eastbound",
      "BSUF-w" => "suffolk_downs_westbound",
      "BWON-m" => "wonderland_mezzanine",
      "BWON-w" => "wonderland_westbound",
      "BWOO-e" => "wood_island_eastbound",
      "BWOO-m" => "wood_island_mezzanine",
      "BWOO-w" => "wood_island_westbound",
      "MBUT-c" => "butler_center",
      "MCAP-n" => "capen_street_inbound",
      "MCAP-s" => "capen_street_outbound",
      "MCED-n" => "cedar_grove_inbound",
      "MCED-s" => "cedar_grove_outbound",
      "MCEN-n" => "central_avenue_inbound",
      "MCEN-s" => "central_avenue_outbound",
      "MMIL-n" => "milton_inbound",
      "MMIL-s" => "milton_outbound",
      "MVAL-n" => "valley_road_inbound",
      "MVAL-s" => "valley_road_outbound",
      "OASQ-m" => "assembly_mezzanine",
      "OASQ-n" => "assembly_northbound",
      "OASQ-s" => "assembly_southbound",
      "OBAC-m" => "back_bay_mezzanine",
      "OBAC-n" => "back_bay_northbound",
      "OBAC-s" => "back_bay_southbound",
      "OCHN-m" => "chinatown_northbound_lobby",
      "OCHN-n" => "chinatown_northbound",
      "OCHS-m" => "chinatown_southbound_lobby",
      "OCHS-s" => "chinatown_southbound",
      "OCOM-m" => "community_college_mezzanine",
      "OCOM-n" => "community_college_northbound",
      "OCOM-s" => "community_college_southbound",
      "ODTN-n" => "orange_downtown_crossing_northbound",
      "ODTS-s" => "orange_downtown_crossing_southbound",
      "OFOR-m" => "forest_hills_main_lobby",
      "OFOR-n" => "forest_hills_northbound",
      "OFOR-s" => "forest_hills_southbound",
      "OGRE-m" => "green_street_mezzanine",
      "OGRE-n" => "green_street_northbound",
      "OGRE-s" => "green_street_southbound",
      "OHAY-m" => "orange_haymarket_mezzanine",
      "OHAY-n" => "orange_haymarket_northbound",
      "OHAY-s" => "orange_haymarket_southbound",
      "OJAC-m" => "jackson_square_mezzanine",
      "OJAC-n" => "jackson_square_northbound",
      "OJAC-s" => "jackson_square_southbound",
      "OMAL-m" => "malden_center_entire_station",
      "OMAS-m" => "mass_ave_mezzanine",
      "OMAS-n" => "mass_ave_northbound",
      "OMAS-s" => "mass_ave_southbound",
      "ONEM-m" => "tufts_mezzanine",
      "ONEM-n" => "tufts_northbound",
      "ONEM-s" => "tufts_southbound",
      "ONST-c" => "orange_north_station_mezzanine",
      "ONST-m" => "orange_north_station_commuter_rail_exit",
      "ONST-n" => "orange_north_station_northbound",
      "ONST-s" => "orange_north_station_southbound",
      "OOAK-e" => "oak_grove_east_busway",
      "OOAK-m" => "oak_grove_mezzanine_southbound",
      "OOAK-n" => "oak_grove_northbound",
      "OOAK-s" => "oak_grove_southbound",
      "OROX-m" => "roxbury_crossing_mezzanine",
      "OROX-n" => "roxbury_crossing_northbound",
      "OROX-s" => "roxbury_crossing_southbound",
      "ORUG-c" => "ruggles_center",
      "ORUG-m" => "ruggles_mezzanine",
      "ORUG-n" => "ruggles_northbound",
      "ORUG-s" => "ruggles_southbound",
      "OSTN-m" => "orange_state_mezzanine",
      "OSTN-n" => "orange_state_northbound",
      "OSTO-m" => "stony_brook_mezzanine",
      "OSTO-n" => "stony_brook_northbound",
      "OSTO-s" => "stony_brook_southbound",
      "OSTS-s" => "orange_state_southbound",
      "OSUL-m" => "sullivan_mezzanine",
      "OSUL-n" => "sullivan_northbound",
      "OSUL-s" => "sullivan_southbound",
      "OWEL-m" => "wellington_mezzanine",
      "OWEL-n" => "wellington_northbound",
      "OWEL-s" => "wellington_southbound",
      "RALE-c" => "alewife_center_southbound",
      "RALE-m" => "alewife_mezzanine_southbound",
      "RAND-m" => "andrew_mezzanine",
      "RAND-n" => "andrew_northbound",
      "RAND-s" => "andrew_southbound",
      "RASH-m" => "ashmont_mezzanine",
      "RASH-n" => "red_ashmont_northbound",
      "RBRA-c" => "braintree_center_northbound",
      "RBRA-m" => "braintree_mezzanine_northbound",
      "RBRO-m" => "broadway_mezzanine",
      "RBRO-n" => "broadway_northbound",
      "RBRO-s" => "broadway_southbound",
      "RCEN-n" => "central_northbound",
      "RCEN-s" => "central_southbound",
      "RDAV-m" => "davis_mezzanine",
      "RDAV-n" => "davis_northbound",
      "RDAV-s" => "davis_southbound",
      "RDTC-n" => "red_downtown_crossing_northbound",
      "RDTC-s" => "red_downtown_crossing_southbound",
      "RFIE-m" => "fields_corner_mezzanine",
      "RFIE-n" => "fields_corner_northbound",
      "RFIE-s" => "fields_corner_southbound",
      "RHAR-m" => "harvard_mezzanine",
      "RHAR-n" => "harvard_northbound",
      "RHAR-s" => "harvard_southbound",
      "RJFK-e" => "jfk_umass_ashmont_platform_northbound",
      "RJFK-m" => "jfk_umass_mezzanine",
      "RJFK-n" => "jfk_umass_braintree_platform_northbound",
      "RJFK-s" => "jfk_umass_braintree_platform_southbound",
      "RJFK-w" => "jfk_umass_ashmont_platform_southbound",
      "RKEN-n" => "kendall_mit_northbound",
      "RKEN-s" => "kendall_mit_southbound",
      "RMGH-n" => "charles_mgh_northbound",
      "RMGH-s" => "charles_mgh_southbound",
      "RNQU-m" => "north_quincy_mezzanine",
      "RNQU-n" => "north_quincy_northbound",
      "RNQU-s" => "north_quincy_southbound",
      "RPOR-m" => "porter_mezzanine",
      "RPOR-n" => "porter_northbound",
      "RPOR-s" => "porter_southbound",
      "RPRK-c" => "red_park_st_center",
      "RPRK-n" => "red_park_st_northbound",
      "RPRK-s" => "red_park_st_southbound",
      "RQUA-m" => "quincy_adams_mezzanine",
      "RQUA-n" => "quincy_adams_northbound",
      "RQUA-s" => "quincy_adams_southbound",
      "RQUC-m" => "quincy_center_mezzanine",
      "RQUC-n" => "quincy_center_northbound",
      "RQUC-s" => "quincy_center_southbound",
      "RSAV-m" => "savin_hill_mezzanine",
      "RSAV-n" => "savin_hill_northbound",
      "RSAV-s" => "savin_hill_southbound",
      "RSHA-m" => "shawmut_mezzanine",
      "RSHA-n" => "shawmut_northbound",
      "RSHA-s" => "shawmut_southbound",
      "RSOU-m" => "red_south_station_mezzanine",
      "RSOU-n" => "red_south_station_northbound",
      "RSOU-s" => "red_south_station_southbound",
      "RWOL-m" => "wollaston_mezzanine",
      "RWOL-n" => "wollaston_northbound",
      "RWOL-s" => "wollaston_southbound",
      "SBOX-e" => "box_district_outbound",
      "SBOX-w" => "box_district_inbound",
      "SBSQ-e" => "bellingham_square_outbound",
      "SBSQ-w" => "bellingham_square_inbound",
      "SCHS-w" => "chelsea_inbound",
      "SCOU-e" => "courthouse_station_outbound",
      "SCOU-m" => "courthouse_station_mezzanine",
      "SEAV-e" => "eastern_ave_outbound",
      "SEAV-w" => "eastern_ave_inbound",
      "SFOR-m" => "forest_hills_entrances_from_busways",
      "SRUG-m" => "ruggles_upper_busway",
      "SSOU-e" => "south_station_silver_line_outbound",
      "SSOU-m" => "south_station_silver_line_arrival_platform",
      "SWTC-e" => "world_trade_center_outbound",
      "SWTC-m" => "world_trade_center_mezzanine"
    }

    internal_to_pretty = (mattapan() ++ blue_line() ++ silver_line() ++ orange_line() ++ red_line()) |> Enum.into(%{})

    id_to_id
    |> Enum.map(fn {arinc_id, internal_id} ->
      {arinc_id, internal_to_pretty[internal_id]}
    end)
    |> Enum.into(%{})
  end
end
