name: Deploy to ECS

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        default: dev
        options:
          - dev
          - dev-green
          - prod

jobs:
  call-workflow:
    uses: mbta/workflows/.github/workflows/deploy-ecs.yml@v2
    with:
      app-name: signs-ui
      environment: ${{ github.event.inputs.environment || 'dev' }}
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
      docker-repo: ${{ secrets.DOCKER_REPO }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
